version: '3.8'

services:
  vite:
    build:
      context: .
      dockerfile: docker/vite/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    ports:
      - '8080:8080'
    command: npm start
